favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5197133
  brandStrength: 0.5
  rhythmicContrast: 1
  brandColors:
    - '#555555'
    - '#367C03'
    - '#A5BB8C'
    - '#3CB100'
    - '#7AA2F4'
  lightness: 0.2688172
typography_spectrum: 0.5179211
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
name: gynanphotography
