name: gynanphotography
favicon: null
layout_spectrum: 0.99902
typography_spectrum: 0.49902
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#505050'
    - '#777777'
    - '#76c12d'
    - '#2e2e2e'
    - '#a5a5a5'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
